spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paper
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  #模板引擎配置
  thymeleaf:
    cache: false
    #suffix: .html  默认后缀
    #prefix: classpath:/templates/  默认前缀
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  druid:
    user: admin
    password: 123456


logging:
  level:
    root: info
    com.ucas.paper: debug
  file: log/paper.log

server:
  port: 8081

file:
  upload:
    path: /home/bruce/Desktop/paperphoto/
  mappath: /imagesupload