spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paper?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  #模板引擎配置
  thymeleaf:
    cache: false
    #suffix: .html  默认后缀
    #prefix: classpath:/templates/  默认前缀
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  druid:
    user: admin
    password: 123456


logging:
  level:
    root: info
    com.ucas.paper: debug
  file: log/paper.log

server:
  port: 80
  address: 0.0.0.0

file:
  upload:
    path: C:/uploadFiles/imagesupload/
  mappath: /imagesupload